/var/spool/torque/mom_priv/jobs/403840.openpbs.mathscluster.ma.ic.ac.uk.SC:96: RuntimeWarning: overflow encountered in exp
  return(np.exp(n_log_price))
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:160: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/var/spool/torque/mom_priv/jobs/403840.openpbs.mathscluster.ma.ic.ac.uk.SC", line 267, in multi_process
    (0, None), (0, None), (0, None), (0, None)])
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/_minimize.py", line 608, in minimize
    return _minimize_powell(fun, x0, args, callback, bounds, **options)
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 2936, in _minimize_powell
    fval=fval)
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 2684, in _linesearch_powell
    xatol=tol / 100)
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 1978, in _minimize_scalar_bounded
    fu = func(x, *args)
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 2682, in <lambda>
    lambda x: myfunc(np.tan(x)),
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 2656, in myfunc
    return func(p + alpha*xi)
  File "/usr/local/lib/python3.6/dist-packages/scipy/optimize/optimize.py", line 427, in function_wrapper
    return function(*(wrapper_args + args))
  File "/var/spool/torque/mom_priv/jobs/403840.openpbs.mathscluster.ma.ic.ac.uk.SC", line 207, in loss_function
    n_sim_stats = cal_stats(n_return=n_sim_return, n_price=n_sim_price)
  File "/var/spool/torque/mom_priv/jobs/403840.openpbs.mathscluster.ma.ic.ac.uk.SC", line 165, in cal_stats
    np.array(price_series2.iloc[:, i]))
  File "/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_base.py", line 519, in fit
    y_numeric=True, multi_output=True)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 824, in check_X_y
    ensure_2d=False, dtype=None)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/spool/torque/mom_priv/jobs/403840.openpbs.mathscluster.ma.ic.ac.uk.SC", line 282, in <module>
    result = pool.map(multi_process, iterations)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
R[write to console]: Warning message:

R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  library ‘/usr/lib/R/site-library’ contains no packages

